apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: whoami
spec:
  hostNetwork: true
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: ricardopereira87/whoami
        ports:
        - containerPort: 88